-- 20 historias reales de la encuesta E1 — columnas reales de la tabla
INSERT INTO contribuciones_historia (nombre, ciudad, anio, historia, tema, estado) VALUES
  ('Motero encuestado','Cuenca','2025','Después de cambiar las pastillas me olvidé de darle el último apriete al cáliper. En plena ruta de tierra empecé a escuchar un golpeteo y pensé que había roto la suspensión. Cuando revisé vi que los pernos estaban casi afuera. De milagro no perdí el freno.','Cáliper','aprobada'),
  ('Motero encuestado','Azogues','2025','Antes de salir dije luego reviso la presión. Grave error. A unos 120 km/h la moto se sentía flotando en las curvas y me asusté bastante. Paré en una gasolinera y la llanta delantera estaba bajísima.','Presión de llantas','aprobada'),
  ('Motero encuestado','Gualaceo','2025','La luz del aceite prendió un ratito y pensé que era un falso contacto. Seguí manejando como si nada. Al llegar revisé la varilla y casi no tenía aceite. Desde ahí no vuelvo a ignorar ninguna luz del tablero.','Aceite','aprobada'),
  ('Motero encuestado','Cuenca','2025','Escuchaba un golpe metálico cada vez que aceleraba pero pensé que era normal. En una parada vi que la cadena estaba tan floja que casi se sale de la corona. Menos mal la revisé a tiempo.','Cadena','aprobada'),
  ('Motero encuestado','Cuenca','2025','Nos metimos por unos caminos llenos de polvo todo el día. La moto empezó a sentirse lenta y ya no quería subir las cuestas como antes. Al llegar a casa saqué el filtro y parecía una piedra de tanta tierra.','Filtro de aire','aprobada'),
  ('Motero encuestado','Cuenca','2025','Estaba saliendo del trabajo y la moto se apagaba cada vez que metía primera. Ya me imaginaba llevándola al taller. Al final era el sensor de la pata lateral que estaba lleno de tierra y hacía mal contacto.','Pata lateral','aprobada'),
  ('Motero encuestado','Azogues','2025','Después de un viaje largo empecé a escuchar una vibración horrible. Pensé que era el motor y ya me estaba preocupando. Resultó que se habían aflojado dos tornillos del escape por las vibraciones.','Tornillos','aprobada'),
  ('Motero encuestado','Cuenca','2025','Pasé por una calle completamente inundada y unos metros después quise frenar. La maneta se sintió rara y casi no frenó al principio porque los discos estaban empapados. Qué susto.','Frenos','aprobada'),
  ('Motero encuestado','Cuenca','2025','Salí del supermercado y la moto no quiso prender. No daba ni un clic. Lo peor fue que la batería ya me había avisado hace semanas y por ahorrar unos días más me tocó empujarla varias cuadras.','Batería','aprobada'),
  ('Motero encuestado','Gualaceo','2025','Planeé regresar antes de que anochezca pero se hizo tarde. Cuando ya estaba oscuro se quemó la luz baja. Me tocó seguir despacio hasta el siguiente pueblo porque no veía casi nada.','Faro','aprobada'),
  ('Motero encuestado','Cuenca','2025','En una subida lenta la temperatura empezó a subir demasiado. Pensé que era normal por el esfuerzo, pero una rama había tapado parte del radiador. La saqué y la temperatura volvió a bajar.','Radiador','aprobada'),
  ('Motero encuestado','Cuenca','2025','Sentía que el embrague cada día estaba más duro pero seguía diciendo después lo ajusto. Un día en medio del tráfico el cable terminó rompiéndose. Ahí sí me tocó llamar ayuda.','Embrague','aprobada'),
  ('Motero encuestado','Cuenca','2025','Antes de salir noté que un espejo estaba un poco flojo y dije aguanta el viaje. A los 80 kilómetros pasó un bache y salió volando. Perdí media hora buscándolo al borde de la carretera.','Espejo','aprobada'),
  ('Motero encuestado','Cuenca','2025','Había tanto barro que el guardabarros delantero se llenó por completo. La rueda casi no giraba y pensé que se había dañado el rodamiento. Solo era barro acumulado.','Guardabarros','aprobada'),
  ('Motero encuestado','Cuenca','2025','El tablero marcaba medio tanque así que seguí tranquilo. En plena avenida la moto se apagó. El sensor del flotador estaba fallando y en realidad ya estaba seco.','Combustible','aprobada'),
  ('Motero encuestado','Azogues','2025','Hice casi mil kilómetros sin acordarme de lubricar la cadena. Empezó a sonar horrible y a sentirse áspera cada vez que aceleraba. Por suerte no pasó a mayores, pero aprendí la lección.','Lubricación','aprobada'),
  ('Motero encuestado','Cuenca','2025','Bajé un poco la presión de las llantas para tener más agarre en tierra. El problema fue que me olvidé de volver a inflarlas antes de regresar por carretera. La moto se sentía pesada y calentaba mucho las llantas.','Llanta','aprobada'),
  ('Motero encuestado','Cuenca','2025','Se prendió la luz del ABS y pensé que ya me iba a tocar gastar plata. Llegué al taller y solo había una piedra pequeña pegada al sensor. Cinco minutos después todo estaba funcionando otra vez.','Sensor ABS','aprobada'),
  ('Motero encuestado','Cuenca','2025','En una salida de noche se empezó a empañar completamente el visor del casco. Abrí un poco para ver mejor y justo entró un insecto directo al ojo. Desde entonces siempre reviso que el pinlock esté bien puesto.','Casco','aprobada'),
  ('Motero encuestado','Cuenca','2025','Le hice mantenimiento yo mismo y cuando terminé estaba orgulloso porque todo quedó bien. Dos días después empecé a escuchar un ruido raro al frenar. Me había olvidado de aplicar torque a los tornillos del disco. Por suerte me di cuenta antes de que pasara algo serio.','Tornillos del disco','aprobada');
SELECT COUNT(*) AS total_historias FROM contribuciones_historia;